config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :articles
  resources :sessions
  resources :users do
  	member do
      get :confirm_email
      get :forget_password
      patch :update_password
    end
  end
  get "create", to: "sessions#create", as: :create_session
  get "forget_password_mail", to: "users#forget_password_mail"
  post :notification, to: 'notification#send'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  before_create :confirmation_token
  has_secure_password
  has_many :articles
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :name, presence: true, length: { in: 3..16 }
  validates :password, presence: true, confirmation: true, length: { in: 6..8 }
  validates :password_confirmation, presence: true
  validates :mobile_number, length: { is: 10 }

  def confirmation_token
  	  byebug
      if self.confirm_token.blank?
          self.confirm_token = SecureRandom.urlsafe_base64.to_s
      end
  end

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end
  
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private   
  def current_user   
    User.where(id: session[:user_id]).first   
  end   
  helper_method :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = current_user.articles
    @article = Article.new
  end

  def new
    @article = current_user.article.new
  end
  def create
    @article =current_user.articles.new(article_params)
    byebug
    if @article.save
      respond_to do |format|
        TwilioTextMessenger.new().call
        format.html { redirect_to @articles, notice: 'Article was successfully created.' }
        format.js
      end
    else
      render :new
    end
  end

  def edit
    @article = Article.find_by(id: params[:id])
  end

  def update
    @article = Article.find_by(id: params[:id])
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to @articles, notice: 'Article was successfully created.' }
          format.js
        end
      end
  end

  def show
  end

  def destroy
    @article = Article.find_by(id: params[:id])
    @article.destroy
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Article was successfully Deleted.' }
        format.js
      end
  end

  private

  def article_params
    params.require(:article).permit(:title, :description);
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notification_controller.rb
class NotificationController < ApplicationController
	def send
		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:email])
  	if user && user.authenticate(params[:password])
  	  if user.email_confirmed   
        session[:user_id] = user.id   
        redirect_to articles_path 
      else
      	render :js => "alert('Please activate your account by following the'+ 
        'instructions in the account confirmation email you received to proceed');"
      end  
    else   
      render :new   
    end   
  end

  def destroy
  	session[:user_id] = nil   
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user= User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		UserMailer.with(user: @user).user_varification.deliver
  		redirect_to root_path
  	else
  		render :new
  	end
  end

  def confirm_email
  	byebug
  	@user = User.find_by(confirm_token: params[:id])
  	if @user
  	  @user.email_activate
  	  redirect_to create_session_path(request.parameters.merge(email: @user.email, password: @user.password))
  	else
  		redirect_to root_path
  	end
  end

  def forget_password_mail
    @user = User.find_by_email(params[:email])
    if @user
      UserMailer.with(user: @user).forget_password_instructions.deliver
      render :js => "alert('Instructions sent to ur mail');"
    else
      render :js => "alert('User not found');"
    end
  end
  
  def forget_password
    byebug
    @user = User.find_by_id(params[:id])
  end

  def update_password
    @user = User.find_by_id(params[:id])
    byebug
    if @user.update(user_params)
      redirect_to new_session_path, :js => "alert('Password Updated Successfully');"
    else
      render :forget_password
    end
  end
    
  def destroy
  end

  private
  def user_params
  	params.require(:user).permit(:name, :email, :mobile_number, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/_article.html.erb
<tr id = "<%=@article.id%>" >
  <td><%= @article.id%></td>
  <td><%= @article.title%></td>
  <td><%= @article.description%></td>
  <td><span class = "edit-article" id = "<%= @article.id%>" >edit</span></td>
  <td><%= link_to("delete",article_path(@article.id), method: :delete, remote: true) %></td>
</tr>

app/views/articles/create.js.erb
var articles = document.querySelector("#show-articles table");
articles.insertAdjacentHTML("beforeend", "<%= j render(@article) %>");
document.querySelector("#new-article-form-div").style.display = "none";
document.querySelector("#show-articles").style.display = "block";

app/views/articles/destroy.js.erb
var row = document.getElementById("<%=@article.id%>");
row.parentNode.removeChild(row);

app/views/articles/index.html.erb
<div class="card card-primary card-outline">    
  <div class="card-header">
    <b>Ticket</b>Management
  </div>

  <div class="card-body">
    <h6 class="card-title">Welcome to ticket management</h6>
    <% if current_user %>
      Logged in as <%= current_user.email %>.  
      <%= link_to "Log Out", session_path(current_user.id), method: :delete %><br/>
      <button class = "btn btn-primary new-article-btn" style = "margin-top: 20px;   margin-left: 20px;">New Article</button>
		<div id = "show-articles">
		  <%= render partial: "layouts/show_articles" %>
		</div>
		<div id = "new-article-form-div" style="display:none; margin-top: 20px;">
		  <%= render partial: "layouts/new_article"%>
		</div>
		<div class = "update-article-form-div" style="display:none; margin-top: 20px;">
		  <%= render partial: "layouts/article_form"%>
		</div>
		<br/> 
   <% else %>
      <p class="card-text">For Using The ticket management Apllication you have to Register yourself on the application if you have already registered Simply click on <b>loging</b> button othrwise Register yourself using <b>signup</b> button</p>
      <%= link_to('SignUp', new_user_path,:class => "btn btn-success") %>
      <%= link_to('LogIn', new_session_path,:class => "btn btn-primary") %>
    <%end%>
  </div>
</div>  
<div>hello</div>

app/views/articles/update.js.erb
alert("update");
document.querySelector(".update-article-form-div").style.display = "none";
var articles = document.querySelector("#show-articles table");
var row = document.getElementById("<%=@article.id%>");
row.parentNode.removeChild(row);
articles.insertAdjacentHTML("beforeend", "<%= j render(@article) %>");
document.querySelector("#show-articles").style.display = "block";

app/views/home/index.html.erb
<div class="card card-primary card-outline">    
  <div class="card-header">
    <b>Ticket</b>Management
  </div>

  <div class="card-body">
    <h6 class="card-title">Welcome to ticket management</h6> 
   <% if !current_user %>
      <p class="card-text">For Using The ticket management Apllication you have to Register yourself on the application if you have already registered Simply click on <b>loging</b> button othrwise Register yourself using <b>signup</b> button</p>
      <%= link_to('SignUp', new_user_path,:class => "btn btn-success") %>
      <%= link_to('LogIn', new_session_path,:class => "btn btn-primary") %>
    <% else %>
    <script type="text/javascript">
    window.location.href="/articles/"  // put your correct path in a string here
    </script>
    <%end%>
  </div>
</div>  

app/views/layouts/_article_form.html.erb
  <div class="card card-warning col-6">
  <div class="card-header">
    <h3 class="card-title">Update Article</h3>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <%= form_for @article, remote: true, :html => { :id => "update-article-form"}, method: :patch do |f| %>
      <div class="row">
        <div class="col-12">
          <!-- text input -->
          <div class="form-group">
            <label>Title</label>
            <%= f.text_field :title, :class => "form-control", id: "title", :placeholder => "Enter ..."%>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <!-- textarea -->
          <div class="form-group">
            <label>Description</label>
            <%= f.text_area :description, :class => "form-control", id: "description", :placeholder => "Enter ..."%>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <%= f.submit "Update", :class => "btn btn-primary ", id: "update-article-btn-submit" %>
      </div>
    <% end %>
  </div>
  <!-- /.card-body -->
</div>

app/views/layouts/_new_article.html.erb
  <div class="card card-warning col-6">
  <div class="card-header">
    <h3 class="card-title">Create Article</h3>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <%= form_for @article, remote: true, :html => { :id => "new-article-form"}  do |f| %>
      <div class="row">
        <div class="col-12">
          <!-- text input -->
          <div class="form-group">
            <label>Text</label>
            <%= f.text_field :title, :class => "form-control", :placeholder => "Enter ..."%>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <!-- textarea -->
          <div class="form-group">
            <label>Textarea</label>
            <%= f.text_area :description, :class => "form-control", :placeholder => "Enter ..."%>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <%= f.submit "Add", :class => "btn btn-primary ", id: "new-article-btn-submit" %>
        <button type="submit" class="btn btn-default float-right">Cancel</button>
      </div>
    <% end %>
  </div>
  <!-- /.card-body -->
</div>

app/views/layouts/_show_articles.html.erb
<div class="row" style = "margin-top: 20px;">
  <div class="col-8">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Articles</h3>

        <div class="card-tools">
          <div class="input-group input-group-sm" style="width: 150px;">
            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

            <div class="input-group-append">
              <button type="submit" class="btn btn-default">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body table-responsive p-0" style="height: 300px;">
        <table class="table table-head-fixed text-nowrap article-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Title</th>
              <th>Description</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <% @articles.each do |article|%>
          <tbody>
            <tr id = "<%=article.id%>">
              <td><%= article.id%></td>
              <td><%= article.title%></td>
              <td><%= article.description%></td>
              <td><span class = "edit-article" id = "<%= article.id%>" >edit</span></td>
              <td><%= link_to("delete",article_path(article.id), method: :delete, remote: true) %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>adminlte-rails-template</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header"%>
    <%= yield %>
  </body>
</html>

app/views/users/forget_password.html.erb
<h2>Forgot your password?</h2>
<%= form_for(@user, url: update_password_user_path(@user.id), html: { method: :patch }) do |f| %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autofocus: true, autocomplete: "new-password",:class => "form-control", :placeholder => "type password" %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autofocus: true, autocomplete: "new-password",:class => "form-control", :placeholder => "Retype password" %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/new.html.erb
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <b>Ticket</b>Management
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">Register a new membership</p>

      <%= form_for @user do |f| %>
        <div class="input-group mb-3">
          <%= f.text_field :name, autofocus: true, autocomplete: "name",:class => "form-control", :placeholder => "Full name" %>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <%= f.email_field :email, autofocus: true, autocomplete: "email",:class => "form-control", :placeholder =>"Email" %>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <%= f.text_field :mobile_number, autofocus: true, autocomplete: "mobile_number" ,:class => "form-control", :placeholder =>"Mobile No"%>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fa fa-phone"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <%= f.password_field :password, autocomplete: "new-password",:class => "form-control", :placeholder => "Password" %>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <%= f.password_field :password_confirmation, autocomplete: "new-password",:class => "form-control", :placeholder => "Retype password" %>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="agreeTerms" name="terms" value="agree">
              <label for="agreeTerms">
               I agree to the <a href="#">terms</a>
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <%= f.submit "Sign up", :class => "btn btn-primary btn-block" %>
          </div>
          <!-- /.col -->
        </div>
      <% end %>
      <a href="<%= new_session_path%>" class="text-center">I already have a membership</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
</body>
<!-- /.register-box -->